# Generated by Django 5.2.6 on 2025-10-17 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have deleted this conversation on their end', related_name='deleted_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
