# Generated by Django 5.2.6 on 2025-12-07 22:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_deleted_by'),
        ('products', '0009_product_average_rating_product_rating_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of product in this deal')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of deal creation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (can be overridden for discounts)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', help_text='Current status of the deal', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the buyer accepted the deal', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the buyer confirmed receipt', null=True)),
                ('buyer', models.ForeignKey(help_text='Buyer receiving this deal offer', on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled this deal (if cancelled)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_deals', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(help_text='Conversation this deal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='chat.conversation')),
                ('farmer', models.ForeignKey(help_text='Farmer/seller creating this deal', on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_farmer', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product being sold in this deal', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='products.product')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_rating', models.PositiveSmallIntegerField(help_text='Rating for the seller (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('seller_comment', models.TextField(blank=True, help_text='Comment about the seller service')),
                ('product_rating', models.PositiveSmallIntegerField(help_text='Rating for the product (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product_comment', models.TextField(blank=True, help_text='Comment about the product quality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.OneToOneField(help_text='The completed deal this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='chat.deal')),
                ('reviewer', models.ForeignKey(help_text='The buyer who wrote this review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status'], name='deals_status_eeb583_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['conversation'], name='deals_convers_10eb6d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['farmer'], name='deals_farmer__0a4927_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['buyer'], name='deals_buyer_i_478312_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['-created_at'], name='deals_created_34f492_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_created_6c5dce_idx'),
        ),
    ]
