# Generated by Django 5.2.6 on 2025-12-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_message_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this deal offer expires (for pending deals)', null=True),
        ),
    ]
