# Generated by Django 5.2.6 on 2025-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_permit',
            field=models.FileField(blank=True, help_text='Business permit document for farmer verification', null=True, upload_to='business_permits/'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_permit_notes',
            field=models.TextField(blank=True, help_text='Admin notes for verification (optional)'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_permit_status',
            field=models.CharField(choices=[('none', 'Not submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text='Verification status for farmer role request', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='business_permit_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time permit status was updated', null=True),
        ),
    ]
