# Generated by Django - notification preferences

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_business_permit_user_business_permit_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_chat',
            field=models.BooleanField(default=True, help_text='Receive notifications for new chat messages'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_permit_decision',
            field=models.BooleanField(default=True, help_text='Receive notifications for business permit decisions'),
        ),
    ]
