# Generated by Django 5.2.6 on 2025-12-07 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_notification_preferences'),
        ('products', '0008_savedcalculation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verification_approve', 'Approved Verification'), ('verification_reject', 'Rejected Verification'), ('verification_reupload', 'Requested Reupload'), ('verification_reset', 'Reset to Pending'), ('product_unlist', 'Unlisted Product'), ('product_restore', 'Restored Product'), ('product_feature', 'Featured Product'), ('product_unfeature', 'Unfeatured Product'), ('user_role_change', 'Changed User Role'), ('user_deactivate', 'Deactivated User'), ('user_reactivate', 'Reactivated User'), ('user_clear_sessions', 'Cleared User Sessions')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='Staff member who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_product', models.ForeignKey(blank=True, help_text='Product affected by this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='products.product')),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
