# Generated by Django 5.2.6 on 2025-12-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_farmer_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average rating from buyers', max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='farmer_rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ratings received as a farmer'),
        ),
    ]
