# Generated by Django 5.2.6 on 2025-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_average_farmer_rating_user_farmer_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='target_conversation_id',
            field=models.IntegerField(blank=True, help_text='Conversation ID affected by this action (stored as ID since conversation may be deleted)', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('verification_approve', 'Approved Verification'), ('verification_reject', 'Rejected Verification'), ('verification_reupload', 'Requested Reupload'), ('verification_reset', 'Reset to Pending'), ('product_unlist', 'Unlisted Product'), ('product_restore', 'Restored Product'), ('product_feature', 'Featured Product'), ('product_unfeature', 'Unfeatured Product'), ('user_role_change', 'Changed User Role'), ('user_deactivate', 'Deactivated User'), ('user_reactivate', 'Reactivated User'), ('user_clear_sessions', 'Cleared User Sessions'), ('conversation_delete', 'Deleted Conversation')], max_length=30),
        ),
    ]
