# Generated by Django 5.2.6 on 2025-10-17 15:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product/crop name', max_length=200)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., kg, pieces, bundles)', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(help_text='Available quantity in stock')),
                ('location', models.CharField(blank=True, help_text='Product location/farm location', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether product is currently available for sale')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured/advertised products (FR-11)')),
                ('total_sales', models.PositiveIntegerField(default=0, help_text='Total units sold (for "Top Products" - FR-11)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
                ('farmer', models.ForeignKey(limit_choices_to={'user_type__in': ['farmer', 'both']}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='products_created_a77fb9_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_is_acti_d79db5_idx'), models.Index(fields=['category', 'is_active'], name='products_categor_9e60b3_idx')],
            },
        ),
    ]
