# Generated by Django 5.2.6 on 2025-10-17 15:49

from django.db import migrations


def add_initial_categories(apps, schema_editor):
    """Add common agricultural product categories"""
    Category = apps.get_model('products', 'Category')
    
    categories = [
        {
            'name': 'Vegetables',
            'description': 'Fresh vegetables including leafy greens, root vegetables, and more'
        },
        {
            'name': 'Fruits',
            'description': 'Fresh fruits including tropical fruits, berries, and citrus'
        },
        {
            'name': 'Grains & Cereals',
            'description': 'Rice, corn, wheat, and other grains'
        },
        {
            'name': 'Herbs & Spices',
            'description': 'Fresh herbs, spices, and seasonings'
        },
        {
            'name': 'Root Crops',
            'description': 'Sweet potato, cassava, taro, and other root crops'
        },
        {
            'name': 'Legumes',
            'description': 'Beans, peas, peanuts, and other legumes'
        },
        {
            'name': 'Poultry & Eggs',
            'description': 'Chicken, duck, eggs, and other poultry products'
        },
        {
            'name': 'Livestock',
            'description': 'Pork, beef, goat, and other livestock products'
        },
        {
            'name': 'Fish & Seafood',
            'description': 'Fresh fish, shellfish, and other seafood'
        },
        {
            'name': 'Processed Goods',
            'description': 'Dried, pickled, or preserved agricultural products'
        },
    ]
    
    for category_data in categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )


def remove_initial_categories(apps, schema_editor):
    """Remove initial categories (reverse migration)"""
    Category = apps.get_model('products', 'Category')
    category_names = [
        'Vegetables', 'Fruits', 'Grains & Cereals', 'Herbs & Spices',
        'Root Crops', 'Legumes', 'Poultry & Eggs', 'Livestock',
        'Fish & Seafood', 'Processed Goods'
    ]
    Category.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories, remove_initial_categories),
    ]
