# Generated by Django 5.2.6 on 2025-12-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_savedcalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcalculation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='savedcalculation',
            name='transport_cost',
        ),
        migrations.AddField(
            model_name='savedcalculation',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current price in markets/malls (optional)', max_digits=10, null=True),
        ),
    ]
